-- ============================================================
-- 005: Tedavi Verileri Import (XLS'den)
-- Toplam: 12 kategori, 293 tedavi
-- ============================================================

-- Tabloları temizle (varsa)
DELETE FROM treatments WHERE true;
DELETE FROM treatment_categories WHERE true;

-- ── 1. Kategoriler ──────────────────────────────────────────
INSERT INTO treatment_categories (name, slug, icon, sort_order, is_active) VALUES
  ('Beyazlatma', 'beyazlatma', '✨', 1, true),
  ('Botoks', 'botoks', '💉', 2, true),
  ('Cerrahi', 'cerrahi', '🔪', 3, true),
  ('Diş Temizliği', 'dis-temizligi', '🪥', 4, true),
  ('Implantoloji', 'implantoloji', '🔩', 5, true),
  ('Oral Diagnoz', 'oral-diagnoz', '🔍', 6, true),
  ('Ortodonti', 'ortodonti', '😁', 7, true),
  ('Pedodonti', 'pedodonti', '👶', 8, true),
  ('Periodontoloji', 'periodontoloji', '🩺', 9, true),
  ('Protez', 'protez', '🔧', 10, true),
  ('Protez Implantüstü', 'protez-implantustu', '⚙️', 11, true),
  ('Tedavi ve Endodonti', 'tedavi-ve-endodonti', '🦷', 12, true);

-- ── 2. Tedaviler tablosu oluştur ──────────────────────────
CREATE TABLE IF NOT EXISTS treatments (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  category_id UUID REFERENCES treatment_categories(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  title_en TEXT DEFAULT '',
  price NUMERIC(12,2) DEFAULT 0,
  discount_rate NUMERIC(5,2) DEFAULT 0,
  cost NUMERIC(12,2) DEFAULT 0,
  currency TEXT DEFAULT 'TL',
  tooth_type INT,
  duration_minutes INT DEFAULT 0,
  exam_type INT,
  is_active BOOLEAN DEFAULT true,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- RLS
ALTER TABLE treatments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "treatments_public_read" ON treatments;
CREATE POLICY "treatments_public_read" ON treatments FOR SELECT USING (true);

-- ── 3. Tedavi verileri ──────────────────────────────────────
-- Beyazlatma
INSERT INTO treatments (category_id, title, title_en, price, discount_rate, cost, currency, tooth_type, duration_minutes, exam_type, sort_order, is_active) VALUES
  ((SELECT id FROM treatment_categories WHERE slug = 'beyazlatma'), 'Beyazlatma 1- Ev', 'Whitening 1 - Home', 5500, 30, 500, 'TL', NULL, 0, NULL, 1, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'beyazlatma'), 'Beyazlatma 2- Ofis (FGM)', 'Whitening 2 - Office (FGM)', 11000, 30, 750, 'TL', NULL, 0, NULL, 2, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'beyazlatma'), 'Beyazlatma 2- Ofis (OPALESCENCE)', 'Whitening 2 - Office (OPALESCENCE)', 13500, 30, 1200, 'TL', NULL, 0, NULL, 3, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'beyazlatma'), 'Beyazlatma 2- Ofis (ZOOM)', 'Whitening 2 - Office (ZOOM)', 16500, 30, 4500, 'TL', NULL, 0, NULL, 4, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'beyazlatma'), 'Beyazlatma 3- Kombine', 'Whitening 3 - Combined', 16500, 30, 1500, 'TL', NULL, 0, NULL, 5, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'beyazlatma'), 'Devital Bleaching', 'Devital Bleaching', 4400, 30, 0, 'TL', NULL, 0, NULL, 6, true);

-- Botoks
INSERT INTO treatments (category_id, title, title_en, price, discount_rate, cost, currency, tooth_type, duration_minutes, exam_type, sort_order, is_active) VALUES
  ((SELECT id FROM treatment_categories WHERE slug = 'botoks'), 'Botoks Uygulaması', 'Botox Application', 14500, 30, 4200, 'TL', NULL, 0, NULL, 7, true);

-- Cerrahi
INSERT INTO treatments (category_id, title, title_en, price, discount_rate, cost, currency, tooth_type, duration_minutes, exam_type, sort_order, is_active) VALUES
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'Açık Eklem Cerrahisi (Tek Taraflı)', 'Open Joint Surgery (Unilateral)', 40585, 30, 0, 'TL', NULL, 0, NULL, 8, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'Alveol Düzeltilmesi (Yarım Çene)', 'Alveolar Correction (Half Jaw)', 4840, 30, 0, 'TL', NULL, 0, NULL, 9, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'Alveol Plastiği (Yarım Çene)', 'Alveolar Plastic Surgery (Half Jaw)', 4420, 30, 0, 'TL', NULL, 0, NULL, 10, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'Alveolit Cerrahi Tedavisi', 'Alveolitis Surgical Treatment', 3790, 30, 0, 'TL', NULL, 0, NULL, 11, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'Apikal Rezeksiyon (Kanal Hariç)', 'Apical Resection (Excluding Canal)', 8800, 30, 0, 'TL', NULL, 0, NULL, 12, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'Apse Drenajı ve Tedavisi (Extraoral)', 'Abscess Drainage and Treatment (Extraoral)', 5770, 30, 0, 'TL', NULL, 0, NULL, 13, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'Apse Drenajı ve Tedavisi (İntraoral)', 'Abscess Drainage and Treatment (Intraoral)', 4480, 30, 0, 'TL', NULL, 0, NULL, 14, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'Artrosentez (Eklem Yıkama)- tek çene', 'Arthrocentesis (Joint Washing) - Single Jaw', 22000, 30, 0, 'TL', NULL, 0, NULL, 15, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'Biyopsi (laboratuvar ücreti dahil)', 'Biopsy (includes lab fee)', 5240, 30, 0, 'TL', NULL, 0, NULL, 16, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'Büyük kist operasyonu', 'Large Cyst Surgery', 33000, 30, 0, 'TL', NULL, 0, NULL, 17, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'Collagane Membran', 'Collagane Membrane', 6600, 30, 0, 'TL', NULL, 0, NULL, 18, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'Çene Kırığı (Basit)', 'Jaw Fracture (Simple)', 11130, 30, 0, 'TL', NULL, 0, NULL, 19, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'Çene Kırığı (Komplike - Materyal Ücreti Hariç)', 'Jaw Fracture (Complicated - Material Fee (Excluded)', 32410, 30, 0, 'TL', NULL, 0, NULL, 20, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'Çene Lüksasyonu', 'Jaw Luxation', 1510, 30, 0, 'TL', NULL, 0, NULL, 21, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'Diş Çekimi (Dijital Anestezi ile)', 'Tooth Extraction (With Digital Anesthesia)', 4750, 30, 0, 'TL', NULL, 0, NULL, 22, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'Epulis Operasyonu', 'Epulis Surgery', 3810, 30, 0, 'TL', NULL, 0, NULL, 23, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'Fibrom Operasyonu', 'Fibroma Surgery', 3400, 30, 0, 'TL', NULL, 0, NULL, 24, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'Genioplasti', 'Genioplasty', 38090, 30, 0, 'TL', NULL, 0, NULL, 25, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'Diş Çekimi (Komplikasyonlu)', 'Tooth Extraction (Complicated)', 5230, 30, 0, 'TL', NULL, 0, NULL, 26, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'Diş Çekimi (20 Yaş)', 'Tooth Extraction (Age 20)', 5950, 30, 0, 'TL', 1, 0, NULL, 27, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'Gömük Diş Çekimi  (Dişeti Altı)', 'Impacted Tooth Extraction (Subgingival)', 8800, 30, 0, 'TL', NULL, 0, NULL, 28, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'Gömük Diş Çekimi  (Kemik Altı)', 'Impacted Tooth Extraction (Subbony)', 11000, 30, 0, 'TL', NULL, 0, NULL, 29, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'İmplant Rehberi (Tam Çene)', 'Implant Guide (Full Jaw)', 5605, 30, 0, 'TL', NULL, 0, NULL, 30, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'Kanama Müdahalesi (Basit)', 'Bleeding Management (Simple)', 1300, 30, 0, 'TL', NULL, 0, NULL, 31, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'Kanama Müdahalesi (Dikişli)', 'Bleeding Management (With Sutures)', 2435, 30, 0, 'TL', NULL, 0, NULL, 32, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'Kemik Genişletme Operasyonu', 'Bone Expansion Surgery', 14455, 30, 0, 'TL', NULL, 0, NULL, 33, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'Kist Operasyonu (Küçük)', 'Cyst Surgery (Small)', 5500, 30, 0, 'TL', NULL, 0, NULL, 34, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'Kist Operasyonu (Büyük)', 'Cyst Surgery (Large)', 17600, 30, 0, 'TL', NULL, 0, NULL, 35, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'Kret Düzeltme', 'Crest Correction', 8800, 30, 0, 'TL', NULL, 0, NULL, 36, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'Nevralji Tedavisi (Alkol Enjeksiyonu)', 'Neuralgia Treatment (Alcohol Injection)', 1070, 30, 0, 'TL', NULL, 0, NULL, 37, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'Nevralji Tedavisi Cerrahi (Nöroktomi vb.)', 'Neuralgia Treatment Surgery (Neurectomy, etc.)', 5380, 30, 0, 'TL', NULL, 0, NULL, 38, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'Odontogenik Tümör Operasyonu (Büyük)', 'Odontogenic Tumor Surgery (Large)', 13400, 30, 0, 'TL', NULL, 0, NULL, 39, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'Odontogenik Tümör Operasyonu (Küçük)', 'Odontogenic Tumor Surgery (Small)', 10970, 30, 0, 'TL', NULL, 0, NULL, 40, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'Ortodontik Tedavi Amaçlı Gömük Dişlerin Üzerinin Açılması', 'Opening of Impacted Teeth for Orthodontic Treatment', 4980, 30, 0, 'TL', NULL, 0, NULL, 41, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'Osteomyelitis veya Osteitis Operasyonu (Tek Çene Basit)', 'Osteomyelitis or Osteitis Surgery (Simple Single Jaw)', 9760, 30, 0, 'TL', NULL, 0, NULL, 42, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'Osteotomi (Tek Çene)', 'Osteotomy (Single Jaw)', 42520, 30, 0, 'TL', NULL, 0, NULL, 43, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'Ototransplantasyon', 'Autotransplantation', 8420, 30, 0, 'TL', NULL, 0, NULL, 44, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'Reimplantasyon', 'Reimplantation', 5725, 30, 0, 'TL', NULL, 0, NULL, 45, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'Reverse Vestioplasti (Tek Çene)', 'Reverse Vestioplasty (Single Jaw)', 24200, 30, 0, 'TL', NULL, 0, NULL, 46, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'Segmental Osteotomi', 'Segmental Osteotomy', 42420, 30, 0, 'TL', NULL, 0, NULL, 47, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'Stomatit Tedavisi', 'Stomitis Treatment', 1180, 30, 0, 'TL', NULL, 0, NULL, 48, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'T.M.E. İçi Enjeksiyon (Tek Taraflı)', 'T.M.E. Intracranial Injection (Unilateral)', 1640, 30, 0, 'TL', NULL, 0, NULL, 49, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'T.M.E. Mekonoterapi', 'T.M.E. Meconotherapy', 1730, 30, 0, 'TL', NULL, 0, NULL, 50, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'Torus Operasyonu (Yarım Çene)', 'Torus Surgery (Half Jaw)', 4710, 30, 0, 'TL', NULL, 0, NULL, 51, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'Tükürük Bezi Kanalından Taş Çıkarma', 'Salivary Gland Duct Stone Removal', 3760, 30, 0, 'TL', NULL, 0, NULL, 52, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'cerrahi'), 'Vestibüloplasti (Tek Çene)', 'Vestibuloplasty (Single Jaw)', 9900, 30, 0, 'TL', NULL, 0, NULL, 53, true);

-- Diş Temizliği
INSERT INTO treatments (category_id, title, title_en, price, discount_rate, cost, currency, tooth_type, duration_minutes, exam_type, sort_order, is_active) VALUES
  ((SELECT id FROM treatment_categories WHERE slug = 'dis-temizligi'), 'Positive Ağız Bakım', 'Positive Oral Care', 5500, 30, 0, 'TL', NULL, 0, NULL, 54, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'dis-temizligi'), 'Positive Smile Care - EMS', 'Positive Smile Care - EMS', 8800, 30, 0, 'TL', NULL, 0, NULL, 55, true);

-- Implantoloji
INSERT INTO treatments (category_id, title, title_en, price, discount_rate, cost, currency, tooth_type, duration_minutes, exam_type, sort_order, is_active) VALUES
  ((SELECT id FROM treatment_categories WHERE slug = 'implantoloji'), 'All-On-Four İmplant Paketi 1- Kore (protez hariç)', 'All-On-Four Implant Package 1 - Korea (excluding prosthesis)', 77000, 30, 0, 'TL', NULL, 0, NULL, 56, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'implantoloji'), 'All-On-Four İmplant Paketi 2- Alman (protez hariç)', 'All-On-Four Implant Package 2 - Germany (excluding prosthesis)', 99000, 30, 0, 'TL', NULL, 0, NULL, 57, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'implantoloji'), 'All-On-Four İmplant Paketi 3- İsviçre (protez hariç)', 'All-On-Four Implant Package 3 - Switzerland (excluding prosthesis)', 148500, 30, 0, 'TL', NULL, 0, NULL, 58, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'implantoloji'), 'Cerrahi Guide', 'Surgical Guide', 5775, 30, 0, 'TL', NULL, 0, NULL, 59, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'implantoloji'), 'Greft Uygulaması', 'Graft Application', 15400, 30, 0, 'TL', NULL, 0, NULL, 60, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'implantoloji'), 'İmplant 1- Ekonomik (protez hariç)', 'Implant 1 - Economic (excluding prosthesis)', 19800, 30, 0, 'TL', 1, 0, NULL, 61, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'implantoloji'), 'İmplant 2- Standart (protez hariç)', 'Implant 2 - Standart (excluding prosthesis)', 26400, 30, 0, 'TL', 1, 0, NULL, 62, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'implantoloji'), 'İmplant 3- Premium (protez hariç)', 'Implant 3 - Premium (excluding prosthesis)', 38500, 30, 0, 'TL', 1, 0, NULL, 63, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'implantoloji'), 'İmplant Çıkartılması (Deimplantasyon)', 'Implant Removal (Deimplantation)', 7150, 30, 0, 'TL', NULL, 0, NULL, 64, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'implantoloji'), 'İmplant Rehberi (Yarım Çene)', 'Implant Guide (Half Chin)', 5060, 30, 0, 'TL', NULL, 0, NULL, 65, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'implantoloji'), 'Kapişon İzalesi - İmplant Üstü Açılması', 'Hood Removal - Opening of Implant Top', 1890, 30, 0, 'TL', NULL, 0, NULL, 66, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'implantoloji'), 'Membran Uygulaması (Tek Diş - Flap Op. ve Membran Ücreti Hariç)', 'Membrane Application (Single Tooth - Excluding Flap Surgery and Membrane Fee)', 675, 30, 0, 'TL', NULL, 0, NULL, 67, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'implantoloji'), 'Peri-İmplantitis (Cerrahi Olmayan) (Tek İmp.)', 'Peri-Implantitis (Non-Surgical) (Single Imp.)', 1500, 30, 0, 'TL', NULL, 0, NULL, 68, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'implantoloji'), 'Peri-İmplantitis (Cerrahi) (Biomaterial ve Membran Ücreti Hariç) (Tek İmp.)', 'Peri-Implantitis (Surgical) (Excluding Biomaterial and Membrane Fee) (Single Imp.)', 3670, 30, 0, 'TL', NULL, 0, NULL, 69, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'implantoloji'), 'Sert Doku Greftleme (Greft Ücreti Hariç)', 'Hard Tissue Grafting (Graft Fee) (Excluded)', 7100, 30, 0, 'TL', NULL, 0, NULL, 70, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'implantoloji'), 'Sert Doku Greftleme 1- Küçük (1cc greft ücreti dahil)', 'Hard Tissue Grafting 1 - Small (1cc graft fee included)', 10040, 30, 0, 'TL', NULL, 0, NULL, 71, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'implantoloji'), 'Sert Doku Greftleme 2- Orta (2cc greft ücreti dahil)', 'Hard Tissue Grafting 2 - Medium (2cc graft fee included)', 12485, 30, 0, 'TL', NULL, 0, NULL, 72, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'implantoloji'), 'Sert Doku Greftleme 3- Büyük (4cc greft ücreti dahil)', 'Hard Tissue Grafting 3 - Large (4cc graft fee included)', 16030, 30, 0, 'TL', NULL, 0, NULL, 73, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'implantoloji'), 'Sinüs Operasyonu (external) (greft ücreti dahil)', 'Sinus Surgery (external) (graft fee included)', 22000, 30, 0, 'TL', NULL, 0, NULL, 74, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'implantoloji'), 'Sinüs Operasyonu (internal)', 'Sinus Surgery (internal)', 6480, 30, 0, 'TL', NULL, 0, NULL, 75, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'implantoloji'), 'Sinüs Plastiği', 'Sinus Plasty', 5160, 30, 0, 'TL', NULL, 0, NULL, 76, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'implantoloji'), 'Yumuşak Doku Greftleme (Greft Ücreti Hariç)', 'Soft Tissue Grafting (Graft Fee Excluded)', 5855, 30, 0, 'TL', NULL, 0, NULL, 77, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'implantoloji'), 'Zigoma İmplant (İmplant Ücreti Hariç)', 'Zygoma Implant (Implant Fee Excluded)', 16630, 30, 0, 'TL', NULL, 0, NULL, 78, true);

-- Oral Diagnoz
INSERT INTO treatments (category_id, title, title_en, price, discount_rate, cost, currency, tooth_type, duration_minutes, exam_type, sort_order, is_active) VALUES
  ((SELECT id FROM treatment_categories WHERE slug = 'oral-diagnoz'), 'Dişhekimi Muayenesi', 'Dentist Examination', 1500, 30, 0, 'TL', NULL, 0, NULL, 79, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'oral-diagnoz'), 'Ortodonti Muayenesi', 'Orthodontic Examination', 1500, 30, 0, 'TL', NULL, 0, NULL, 80, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'oral-diagnoz'), 'Pedodonti Kontrol Muayenesi', 'Pediatric Follow-up Examination', 1760, 30, 0, 'TL', NULL, 0, NULL, 81, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'oral-diagnoz'), 'Pedodonti Uzman Muayene', 'Pediatric Specialist Examination', 2200, 30, 0, 'TL', NULL, 0, NULL, 82, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'oral-diagnoz'), 'Antero-Posterior Sefalometrik Film', 'Antero-Posterior Cephalometric Film', 1040, 30, 0, 'TL', NULL, 0, NULL, 83, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'oral-diagnoz'), 'Bilgisayarlı Tomografi (tek çene)', 'Computed Tomography (Single Jaw)', 2160, 30, 0, 'TL', NULL, 0, NULL, 84, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'oral-diagnoz'), 'Diş Röntgen Filmi (Periapikal)', 'Dental X-Ray Film (Periapical)', 340, 30, 0, 'TL', NULL, 0, NULL, 85, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'oral-diagnoz'), 'El Bilek Filmi', 'Wrist X-Ray', 1040, 30, 0, 'TL', NULL, 0, NULL, 86, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'oral-diagnoz'), 'İntra Oral Dijital Radyografi', 'Intra-Oral Digital Radiography', 500, 30, 0, 'TL', NULL, 0, NULL, 87, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'oral-diagnoz'), 'Lateral Sefalometrik Film', 'Lateral Cephalometric Film', 1120, 30, 0, 'TL', NULL, 0, NULL, 88, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'oral-diagnoz'), 'Panaromik Film', 'Panoramic Film', 1650, 30, 0, 'TL', NULL, 0, NULL, 89, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'oral-diagnoz'), 'Tomografi (Bölgesel)', 'Tomography (Regional)', 1200, 30, 0, 'TL', NULL, 0, NULL, 90, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'oral-diagnoz'), 'Tomografi (İki Çene Çene)', 'Tomography (Bilateral) (Jaw-to-Jaw)', 3700, 30, 0, 'TL', NULL, 0, NULL, 91, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'oral-diagnoz'), 'Tomografi (Tek Çene)', 'Tomography (Single Jaw)', 2970, 30, 0, 'TL', NULL, 0, NULL, 92, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'oral-diagnoz'), 'Vitalite Kontrolü (Diş Başına)', 'Vitality Check (Per Tooth)', 110, 30, 0, 'TL', NULL, 0, NULL, 93, true);

-- Ortodonti
INSERT INTO treatments (category_id, title, title_en, price, discount_rate, cost, currency, tooth_type, duration_minutes, exam_type, sort_order, is_active) VALUES
  ((SELECT id FROM treatment_categories WHERE slug = 'ortodonti'), 'Ortodontik Tedavi Metal', 'Orthodontic Treatment Metal', 95500, 30, 10000, 'TL', NULL, 0, NULL, 94, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'ortodonti'), 'Ortodontik Tedavi Porselen', 'Orthodontic Treatment Porcelain', 120500, 30, 10000, 'TL', NULL, 0, NULL, 95, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'ortodonti'), 'Invisalign ClinCheck (Tedavi Planlama Simülasyonu)', 'Invisalign ClinCheck (Treatment Planning Simulation)', 3300, 30, 0, 'TL', NULL, 0, NULL, 96, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'ortodonti'), 'Invisalign Comprehensive Full', 'Invisalign Comprehensive Full', 154000, 30, 52000, 'TL', NULL, 0, NULL, 97, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'ortodonti'), 'Invisalign First (Çift Çene)', 'Invisalign First (Double Jaw)', 88000, 30, 0, 'TL', NULL, 0, NULL, 98, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'ortodonti'), 'Invisalign First (Tek Çene)', 'Invisalign First (Single Jaw)', 55000, 30, 0, 'TL', NULL, 0, NULL, 99, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'ortodonti'), 'Invisalign First Faz 2 Comprehensive', 'Invisalign First Phase 2 Comprehensive', 99000, 30, 0, 'TL', NULL, 0, NULL, 100, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'ortodonti'), 'Invisalign Lite (Çift Çene)', 'Invisalign Lite (Double Jaw)', 99000, 30, 35000, 'TL', NULL, 0, NULL, 101, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'ortodonti'), 'Invisalign Lite (Tek Çene)', 'Invisalign Lite (Single Jaw)', 99000, 30, 35000, 'TL', NULL, 0, NULL, 102, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'ortodonti'), 'Invisalign Ortognatik Class 2-3', 'Invisalign Orthognathic Class 2-3', 198000, 30, 0, 'TL', NULL, 0, NULL, 103, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'ortodonti'), 'Açık Kapanışın Ortodontik Tedavisi', 'Orthodontic Treatment of Open Bite', 31040, 30, 0, 'TL', NULL, 0, NULL, 104, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'ortodonti'), 'Ağız Dışı Aparey Tatbiki (Headgear - Chincap)', 'Extraoral Appliance Fitting (Headgear - Chincap)', 28600, 30, 0, 'TL', NULL, 0, NULL, 105, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'ortodonti'), 'Ağız İçi Distalizasyon Apareyi (Pendex vb.)', 'Intraoral Distalization Appliance (Pendex, etc.)', 28600, 30, 0, 'TL', NULL, 0, NULL, 106, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'ortodonti'), 'Aparey Tamiri', 'Appliance Repair', 2200, 30, 0, 'TL', NULL, 0, NULL, 107, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'ortodonti'), 'Aparey Tekrarı (tek çene)', 'Appliance Reconstruction (Single Jaw)', 11000, 30, 0, 'TL', NULL, 0, NULL, 108, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'ortodonti'), 'Bantlı Rme', 'Banded Removal', 27500, 30, 0, 'TL', NULL, 0, NULL, 109, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'ortodonti'), 'Braket Tamiri', 'Bracket Repair', 1650, 30, 0, 'TL', NULL, 0, NULL, 110, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'ortodonti'), 'Buton Takma', 'Button Fitting', 8800, 30, 0, 'TL', NULL, 0, NULL, 111, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'ortodonti'), 'Büküm İçeren Tel Tatbiki (Tek Çene)', 'Bending Wire Fitting (Single Jaw)', 1325, 30, 0, 'TL', NULL, 0, NULL, 112, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'ortodonti'), 'Çift Çeneyi İlgilendiren Aparey Yapımı (Frankel Aygıtları - Aktivatör - Bionatör)', 'Binary Appliance Fabrication (Frankel Appliances - Activator) - Bionator)', 28600, 30, 0, 'TL', NULL, 0, NULL, 113, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'ortodonti'), 'Debonging (Braket Sökümü)', 'Debonging (Bracket Removal)', 4400, 30, 0, 'TL', NULL, 0, NULL, 114, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'ortodonti'), 'Dento Alveolar Distraksiyon', 'Dento-Alveolar Distraction', 59400, 30, 0, 'TL', NULL, 0, NULL, 115, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'ortodonti'), 'Essix (tek çene)', 'Essix (Single Jaw)', 2200, 30, 0, 'TL', NULL, 0, NULL, 116, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'ortodonti'), 'FaceMask+Hyrax', 'FaceMask + Hyrax', 39600, 30, 0, 'TL', NULL, 0, NULL, 117, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'ortodonti'), 'Gömük Diş Operasyonu', 'Impacted Tooth Surgery', 9900, 30, 0, 'TL', NULL, 0, NULL, 118, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'ortodonti'), 'Hareketli Tedavi', 'Removable Treatment', 28600, 30, 0, 'TL', NULL, 0, NULL, 119, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'ortodonti'), 'HeadGear,Monoblok,Distalizasyon', 'HeadGear, Monoblock, Distalization', 28600, 30, 0, 'TL', NULL, 0, NULL, 120, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'ortodonti'), 'Mini Vida', 'Mini Screw', 4970, 30, 0, 'TL', NULL, 0, NULL, 121, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'ortodonti'), 'Ortodontik Retainer Tamiri', 'Orthodontic Retainer Repair', 2200, 30, 0, 'TL', NULL, 0, NULL, 122, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'ortodonti'), 'Ortognatik Cerrahi I-II-III (metal)', 'Orthognathic Surgery I-II-III (Metal)', 132000, 30, 0, 'TL', NULL, 0, NULL, 123, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'ortodonti'), 'Ortognatik Cerrahi I-II-III (porselen)', 'Orthognathic Surgery I-II-III (Porcelain)', 143000, 30, 0, 'TL', NULL, 0, NULL, 124, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'ortodonti'), 'Retainer Takılması (Tek Çene)', 'Retainer Installation (Single Jaw)', 9900, 30, 0, 'TL', NULL, 0, NULL, 125, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'ortodonti'), 'Seviyeleme (Tek Diş)', 'Leveling (Single Tooth)', 7700, 30, 0, 'TL', NULL, 0, NULL, 126, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'ortodonti'), 'Seviyeleme Tedavisi Metal', 'Leveling Treatment Metal', 35750, 30, 0, 'TL', NULL, 0, NULL, 127, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'ortodonti'), 'Seviyeleme Tedavisi Porselen', 'Leveling Treatment Porcelain', 49710, 30, 0, 'TL', NULL, 0, NULL, 128, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'ortodonti'), 'Invisalign Moderate (Çift Çene)', 'Invisalign Moderate (Çift Çene)', 121000, 30, 45000, 'TL', 1, 0, NULL, 129, true);

-- Pedodonti
INSERT INTO treatments (category_id, title, title_en, price, discount_rate, cost, currency, tooth_type, duration_minutes, exam_type, sort_order, is_active) VALUES
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Daimi Diş Kanal Tedavisi - 1 Kanal (Dolgu Hariç)', 'Permanent Tooth Root Canal Treatment - 1 Canal (Excluding Filling)', 6350, 30, 0, 'TL', NULL, 0, NULL, 130, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Daimi Diş Kanal Tedavisi - 2 Kanal (Dolgu Hariç)', 'Permanent Tooth Root Canal Treatment - 2 Canals (Excluding Filling)', 8500, 30, 0, 'TL', NULL, 0, NULL, 131, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Daimi Diş Kanal Tedavisi - 3 Kanal (Dolgu Hariç)', 'Permanent Tooth Root Canal Treatment - 3 Canals (Excluding Filling)', 9500, 30, 0, 'TL', NULL, 0, NULL, 132, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Daimi Diş Kanal Tedavisi - 4 Kanal (Dolgu Hariç)', 'Permanent Tooth Root Canal Treatment - 4 Canals (Excluding Filling)', 11000, 30, 0, 'TL', NULL, 0, NULL, 133, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Daimi Diş MTA Amputasyon (Dolgu Hariç)', 'Permanent Tooth MTA Amputation (Excluding Filling)', 9150, 30, 0, 'TL', NULL, 0, NULL, 134, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Daimi Diş Paslanmaz Çelik Kuron', 'Permanent Dental Stainless Steel Crown', 6160, 30, 0, 'TL', NULL, 0, NULL, 135, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Detertraj (Çift Çene)', 'Scaling (Double Jaw)', 3545, 30, 0, 'TL', NULL, 0, NULL, 136, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Detertraj (Tek Çene)', 'Scaling (Single Jaw)', 2370, 30, 0, 'TL', NULL, 0, NULL, 137, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Endokuron', 'Endocrown', 10830, 30, 0, 'TL', NULL, 0, NULL, 138, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Fissür Örtücü', 'Fissure Sealant', 2650, 30, 0, 'TL', NULL, 0, NULL, 139, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Flor Uygulaması (Polisaj Dahil) (Çift Çene)', 'Fluoride Application (Polishing Included) (Double Jaw)', 4150, 30, 0, 'TL', NULL, 0, NULL, 140, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Flor Uygulaması (Polisaj Dahil) (Tek Çene)', 'Fluoride Application (Polishing Included) (Single Jaw)', 2090, 30, 0, 'TL', NULL, 0, NULL, 141, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Hareketli Yer Tutucu', 'Removable Space Maintainer', 9100, 30, 0, 'TL', NULL, 0, NULL, 142, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Kanal Pansuman', 'Root Canal Dressing', 1925, 30, 0, 'TL', NULL, 0, NULL, 143, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Kuafaj (Sinir Koruması)', 'Caption (Nerve Protection)', 995, 30, 0, 'TL', NULL, 0, NULL, 144, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Lingual Ark', 'Lingual Arch', 9100, 30, 0, 'TL', NULL, 0, NULL, 145, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'MTA Kuafaj', 'MTA Caption', 1690, 30, 0, 'TL', NULL, 0, NULL, 146, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Palatinal Ark', 'Palatinal Arch', 9100, 30, 0, 'TL', NULL, 0, NULL, 147, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Pedodontik Zirkonyum Kuron', 'Pedodontic Zirconium Crown', 7320, 30, 0, 'TL', NULL, 0, NULL, 148, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Rejeneratif Kanal Tedavisi (Dolgu Hariç)', 'Regenerative Root Canal Treatment (Without Filling)', 12920, 30, 0, 'TL', NULL, 0, NULL, 149, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Rezin İnfilitrasyonu Tedavisi', 'Resin Infiltration Treatment', 6800, 30, 0, 'TL', NULL, 0, NULL, 150, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Sabit Yer Tutucu', 'Fixed Space Maintainer', 8800, 30, 0, 'TL', NULL, 0, NULL, 151, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Splint Uygulaması', 'Splint Application', 6350, 30, 0, 'TL', NULL, 0, NULL, 152, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Strip Kron', 'Strip Crown', 1860, 30, 0, 'TL', NULL, 0, NULL, 153, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Süt Dişi Amputasyon(MTA) + Dolgu', 'Deciduous Tooth Amputation (MTA) + Filling', 7860, 30, 0, 'TL', NULL, 0, NULL, 154, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Süt Dişi Amputasyon(MTA) + PÇK', 'Deciduous Tooth Amputation (MTA) + PÇK', 9140, 30, 0, 'TL', NULL, 0, NULL, 155, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Süt Dişi Çekimi (Dijital Anestezi İle)', 'Deciduous Tooth Extraction (With Digital Anesthesia)', 2310, 30, 0, 'TL', NULL, 0, NULL, 156, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Süt Dişi Çekimi (Topikal Anestezi İle)', 'Deciduous Tooth Extraction (With Topical Anesthesia)', 1815, 30, 0, 'TL', NULL, 0, NULL, 157, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Süt Dişi Kanal Tedavisi (1 Kanal, Dolgu Hariç)', 'Deciduous Tooth Root Canal Treatment (1 Canal, (Excluding Filling)', 3570, 30, 0, 'TL', NULL, 0, NULL, 158, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Süt Dişi Kanal Tedavisi (2 Kanal, Dolgu Hariç)', 'Deciduous Tooth Root Canal Treatment (2 Root Canals, Excluding Filling)', 4320, 30, 0, 'TL', NULL, 0, NULL, 159, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Süt Dişi Kanal Tedavisi (3 Kanal, Dolgu Hariç)', 'Deciduous Tooth Root Canal Treatment (3 Root Canals, Excluding Filling)', 4960, 30, 0, 'TL', NULL, 0, NULL, 160, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Süt Dişi Kompozit Dolgu 1 Yüzlü (Kole)', 'Deciduous Tooth Composite Filling (1-Sided)', 2695, 30, 0, 'TL', NULL, 0, NULL, 161, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Süt Dişi Kompozit Dolgu 1 Yüzlü (O)', 'Deciduous Tooth Composite Filling (1-Sided)', 3245, 30, 0, 'TL', NULL, 0, NULL, 162, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Süt Dişi Kompozit Dolgu 2 Yüzlü (DO)', 'Deciduous Tooth Composite Filling (2-Sided)', 3465, 30, 0, 'TL', NULL, 0, NULL, 163, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Süt Dişi Kompozit Dolgu 2 Yüzlü (MO)', 'Deciduous Tooth Composite Filling (2-Sided)', 3465, 30, 0, 'TL', NULL, 0, NULL, 164, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Süt Dişi Kompozit Dolgu 3 Yüzlü (MOD)', 'Deciduous Tooth Composite Filling (3-Sided)', 4125, 30, 0, 'TL', NULL, 0, NULL, 165, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Süt Dişi MTA Amputasyon (Dolgu Hariç)', 'Deciduous Tooth MTA Amputation (Excluding Filling)', 5825, 30, 0, 'TL', NULL, 0, NULL, 166, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Süt Kanal Tedavisi + PÇK', 'Deciduous Root Canal Treatment + PSC', 9560, 30, 0, 'TL', NULL, 0, NULL, 167, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Travma Splinti', 'Trauma Splint', 8560, 30, 0, 'TL', NULL, 0, NULL, 168, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Yer Tutucu (Hareketli)', 'Space Maintainer (Movable)', 9100, 30, 0, 'TL', NULL, 0, NULL, 169, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Yer Tutucu (Sabit)', 'Space Maintainer (Fixed)', 8800, 30, 0, 'TL', NULL, 0, NULL, 170, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Yüzeysel Flor Uygulaması (Yarım Çene)', 'Superficial Fluoride Application (Half Jaw)', 720, 30, 0, 'TL', NULL, 0, NULL, 171, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Süt Dişi Paslanmaz Çelik Kuron', 'Permanent Dental Stainless Steel Crown', 4560, 30, 0, 'TL', NULL, 0, NULL, 172, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Polisaj(Çift Çene)', 'Scaling (Single Jaw)', 2970, 30, 0, 'TL', NULL, 0, NULL, 173, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Strip Kron (Dolgu Hariç)', 'Strip Crown', 2460, 30, 0, 'TL', NULL, 0, NULL, 174, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Süt Dişi Çekimi (Lokal Anestezi İle)', 'Deciduous Tooth Extraction (With Digital Anesthesia)', 2810, 30, 0, 'TL', NULL, 0, NULL, 175, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Daimi Diş Kompozit Dolgu 1 Yüzlü (Kole)', 'Deciduous Tooth Composite Filling (1-Sided)', 3800, 30, 0, 'TL', NULL, 0, NULL, 176, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Daimi Dişi Kompozit Dolgu 1 Yüzlü (O)', 'Deciduous Tooth Composite Filling (1-Sided)', 3800, 30, 0, 'TL', NULL, 0, NULL, 177, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Daimi Dişi Kompozit Dolgu 2 Yüzlü (MO/DO)', 'Deciduous Tooth Composite Filling (1-Sided)', 4655, 30, 0, 'TL', NULL, 0, NULL, 178, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'pedodonti'), 'Daimi Dişi Kompozit Dolgu 3 Yüzlü (MOD)', 'Deciduous Tooth Composite Filling (1-Sided)', 5240, 30, 0, 'TL', NULL, 0, NULL, 179, true);

-- Periodontoloji
INSERT INTO treatments (category_id, title, title_en, price, discount_rate, cost, currency, tooth_type, duration_minutes, exam_type, sort_order, is_active) VALUES
  ((SELECT id FROM treatment_categories WHERE slug = 'periodontoloji'), 'Bağ Dokusu Grefti (BDG)', 'Connective Tissue Graft (BTG)', 16500, 30, 0, 'TL', NULL, 0, NULL, 180, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'periodontoloji'), 'Depigmentasyon (Lazerle, Tek Çene)', 'Depigmentation (Laser, Single Jaw)', 9875, 30, 0, 'TL', NULL, 0, NULL, 181, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'periodontoloji'), 'Dudak Konumlandırması (Lip Repositioning)', 'Lip Repositioning (Lip Repositioning)', 39440, 30, 0, 'TL', NULL, 0, NULL, 182, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'periodontoloji'), 'Epulis Operasyonu (Flapli) (Tek Çene)', 'Epulis Surgery (With Flap) (Single Jaw)', 6860, 30, 0, 'TL', NULL, 0, NULL, 183, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'periodontoloji'), 'Epulis Operasyonu (Laserli) (Tek Çene)', 'Epulis Surgery (With Laser) (Single Jaw)', 3910, 30, 0, 'TL', NULL, 0, NULL, 184, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'periodontoloji'), 'Fiberotomi', 'Fiberotomy', 860, 30, 0, 'TL', NULL, 0, NULL, 185, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'periodontoloji'), 'Flap Operasyonu (Subgingival Küretaj Dahil - Tek Diş)', 'Flap Surgery (Including Subgingival Curettage - Single Tooth)', 2730, 30, 0, 'TL', NULL, 0, NULL, 186, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'periodontoloji'), 'Flap Operasyonu (Tek Bölge)', 'Flap Surgery (Single Site)', 9350, 30, 0, 'TL', NULL, 0, NULL, 187, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'periodontoloji'), 'Frenektomi (Flapli)', 'Frenectomy (With Flap)', 8250, 30, 0, 'TL', NULL, 0, NULL, 188, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'periodontoloji'), 'Frenektomi (Laserli)', 'Frenectomy (With Laser)', 8250, 30, 0, 'TL', NULL, 0, NULL, 189, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'periodontoloji'), 'Gingivektomi (Laserli) (Çeyrek Çene)', 'Gingivectomy (With Laser) (Quadrant Jaw)', 6680, 30, 0, 'TL', NULL, 0, NULL, 190, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'periodontoloji'), 'Gingivektomi (Tek Diş)', 'Gingivectomy (Single Tooth)', 2200, 30, 0, 'TL', NULL, 0, NULL, 191, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'periodontoloji'), 'Gingivektomi Kemik Kaldırmalı (tek diş)', 'Gingivectomy with Bone Removal (Single Tooth)', 3850, 30, 0, 'TL', NULL, 0, NULL, 192, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'periodontoloji'), 'Gingivoplasti (Flapli) (Çeyrek Çene)', 'Gingivoplasty (With Flap) (Quadrant Jaw)', 15400, 30, 0, 'TL', NULL, 0, NULL, 193, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'periodontoloji'), 'Gingivoplasti (Tek Diş)', 'Gingivoplasty (Single Tooth)', 2750, 30, 0, 'TL', NULL, 0, NULL, 194, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'periodontoloji'), 'Hemiseksiyon (Kök Amputasyonu - Kanal Tedavisi Hariç)', 'Hemisection (Root Amputation - Excludes Root Canal Treatment)', 2165, 30, 0, 'TL', NULL, 0, NULL, 195, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'periodontoloji'), 'Kök Amputasyonu (Bir Kökün Çıkarılması)', 'Root Amputation (Removal of a Root)', 3440, 30, 0, 'TL', NULL, 0, NULL, 196, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'periodontoloji'), 'Lazer + SRP (Scaling Root Planing - Tek Diş)', 'Laser + SRP (Scaled Root Planning - Single Tooth)', 1380, 30, 0, 'TL', NULL, 0, NULL, 197, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'periodontoloji'), 'Lazerle Dişeti Dezenfeksiyonu ve BioStimülasyon (Tek Çene)', 'Laser Gingival Disinfection and BioStimulation (Single Jaw)', 8800, 30, 0, 'TL', NULL, 0, NULL, 198, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'periodontoloji'), 'Lazerli Dişeti Cerrahisi (Tek Diş)', 'Laser Gingival Surgery (Single Tooth)', 1195, 30, 0, 'TL', NULL, 0, NULL, 199, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'periodontoloji'), 'Papil Oluşturma (Cerrahi Olmayan) (Tek Papil)', 'Papilation (Non-Surgical) (Single Papilla)', 2200, 30, 0, 'TL', NULL, 0, NULL, 200, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'periodontoloji'), 'Papil Oluşturma (Cerrahi) (Tek Papil)', 'Papilation (Surgical) (Single Papilla)', 8800, 30, 0, 'TL', NULL, 0, NULL, 201, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'periodontoloji'), 'Periodontal Apse Tedavisi', 'Periodontal Abscess Treatment', 3300, 30, 0, 'TL', NULL, 0, NULL, 202, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'periodontoloji'), 'Periodontal Splint (Daimi)', 'Periodontal Splint (Permanent)', 7700, 30, 0, 'TL', NULL, 0, NULL, 203, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'periodontoloji'), 'Periodontal Splint (Geçici)', 'Periodontal Splint (Temporary)', 5500, 30, 0, 'TL', NULL, 0, NULL, 204, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'periodontoloji'), 'Saplı yumuşak doku grefti (Koronale Kaydırma, Yana Kaydırma,Tek Diş)', 'Pedipal Soft Tissue Graft (Coronal Shift, Lateral Shift, Single Tooth)', 5970, 30, 0, 'TL', NULL, 0, NULL, 205, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'periodontoloji'), 'Serbest Diş Eti Grefti (Tek Diş)', 'Free Gingival Graft (Single Tooth)', 6810, 30, 0, 'TL', NULL, 0, NULL, 206, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'periodontoloji'), 'Serbest Dişeti Grefti (SDG) (Tek Diş)', 'Free Gingival Graft (FGG) (Single Tooth)', 16500, 30, 0, 'TL', NULL, 0, NULL, 207, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'periodontoloji'), 'Splintleme (Fiberli)', 'Splinting (Fiberized)', 8210, 30, 0, 'TL', NULL, 0, NULL, 208, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'periodontoloji'), 'Subepitelyal Bağ Dokusu Grefti', 'Subepithelial Connective Tissue Graft', 7315, 30, 0, 'TL', NULL, 0, NULL, 209, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'periodontoloji'), 'Subgingival İlaç Uygulaması', 'Subgingival Drug Application', 550, 30, 0, 'TL', NULL, 0, NULL, 210, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'periodontoloji'), 'Subgingival Küretaj (Tek Bölge)', 'Subgingival Curettage (Single Area)', 6050, 30, 0, 'TL', NULL, 0, NULL, 211, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'periodontoloji'), 'Subgingival Küretaj (Tek Diş)', 'Subgingival Curettage (Single Tooth)', 1155, 30, 0, 'TL', NULL, 0, NULL, 212, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'periodontoloji'), 'Vestibül Plak (Diş Eti Protezi - Çene Başına)', 'Vestibule Plate (Gum Prosthesis - Jaw Head)', 4820, 30, 0, 'TL', NULL, 0, NULL, 213, true);

-- Protez
INSERT INTO treatments (category_id, title, title_en, price, discount_rate, cost, currency, tooth_type, duration_minutes, exam_type, sort_order, is_active) VALUES
  ((SELECT id FROM treatment_categories WHERE slug = 'protez'), 'Dijital Gülüş Tasarımı', 'Digital Smile Design', 6050, 30, 0, 'TL', NULL, 0, NULL, 214, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez'), 'Porselen Lamina/Veneer', 'Porcelain Laminate/Veneer', 25000, 30, 0, 'TL', 1, 0, NULL, 215, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez'), 'Empress / E-max Kuron (Full Porselen)', 'Empress / E-max Crown (Full Porcelain)', 25000, 30, 0, 'TL', 1, 0, NULL, 216, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez'), 'Zirkonya Kuron (Monolitik)', 'Zirconia Crown (Monolithic)', 13200, 30, 0, 'TL', 1, 0, NULL, 217, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez'), 'Zirkonya Kuron (Tabakalama)', 'Zirconia Crown (Layered)', 15400, 30, 0, 'TL', 1, 0, NULL, 218, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez'), 'Metal Destekli Porselen Kuron (MDP)', 'Metal-Supported Porcelain Crown (MDP)', 7700, 30, 0, 'TL', NULL, 0, NULL, 219, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez'), 'Geçici Kuron (Tek Diş İçin)', 'Temporary Crown (Single Tooth)', 1650, 30, 0, 'TL', NULL, 0, NULL, 220, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez'), 'Endokuron', 'Endocrown', 11000, 30, 0, 'TL', NULL, 0, NULL, 221, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez'), 'Porselen Dolgu Inley-Onley', 'Porcelain Filling Inlay-Onlay', 14850, 30, 0, 'TL', 1, 0, NULL, 222, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez'), 'Kompozit Inley-Onley', 'Composite Inlay-Onlay', 9150, 30, 0, 'TL', NULL, 0, NULL, 223, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez'), 'Maryland Köprü (Kompozit)', 'Maryland Bridge (Composite)', 8250, 30, 0, 'TL', NULL, 0, NULL, 224, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez'), 'Maryland Köprü (Porselen)', 'Maryland Bridge (Porcelain)', 19250, 30, 0, 'TL', NULL, 0, NULL, 225, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez'), 'Simantasyon (Kuron)', 'Cementation (Crown)', 1225, 30, 0, 'TL', NULL, 0, NULL, 226, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez'), 'Simantasyon (Lamina)', 'Cementation (Laminate)', 1770, 30, 0, 'TL', NULL, 0, NULL, 227, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez'), 'Eklem Splinti (Akrilik)', 'Joint Splint (Acrylic)', 11000, 30, 0, 'TL', NULL, 0, NULL, 228, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez'), 'Gece Plağı (Sert Plak- Diş Gıcırdatma İçin)', 'Night Plate (Hard Plate - For Teeth Grinding)', 9500, 30, 500, 'TL', NULL, 0, NULL, 229, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez'), 'Sporcu Plağı (3 Kat Koruyuculu)', 'Athlete Plate (3-Layer Protector)', 12650, 30, 700, 'TL', NULL, 0, NULL, 230, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez'), 'Besleme (Protezaltı)', 'Suspension (Under Denture)', 7700, 30, 0, 'TL', NULL, 0, NULL, 231, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez'), 'Besleme (Tek Çene)', 'Suspension (Single Jaw)', 5040, 30, 0, 'TL', NULL, 0, NULL, 232, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez'), 'Protez Tamiri', 'Denture Repair', 3300, 30, 0, 'TL', NULL, 0, NULL, 233, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez'), 'Bölümlü Protez (Akrilik - Tek Çene)', 'Partial Denture (Acrylic - Single Jaw)', 14500, 30, 0, 'TL', NULL, 0, NULL, 234, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez'), 'Bölümlü Protez (Döküm Metal ile Güçlendirilmiş - Tek Çene)', 'Partial Denture (Cast Metal Reinforced - Single Jaw)', 19060, 30, 0, 'TL', NULL, 0, NULL, 235, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez'), 'Bölümlü Hareketli Protez (HBP)(Tek Çene)', 'Partial Removable Denture (MDR) (Single Jaw)', 55000, 30, 0, 'TL', NULL, 0, NULL, 236, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez'), 'Diş İlavesi (Tek Diş)', 'Missing Tooth (Single Tooth)', 2225, 30, 0, 'TL', NULL, 0, NULL, 237, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez'), 'Diş Üstü Protezi (Overdenture - Tek Çene) (**)', 'Overdenture (Single Jaw) (**)', 13580, 30, 0, 'TL', NULL, 0, NULL, 238, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez'), 'Düşmüş Kuron ve Köprü Simantasyonu (Her Sabit Üye İçin)', 'Cementation of Fallen Crowns and Bridges (For Each Fixed Member)', 630, 30, 0, 'TL', NULL, 0, NULL, 239, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez'), 'Geçici Hareketli Protez (Tek Çene)', 'Temporary Removable Denture (Single Jaw)', 21000, 30, 0, 'TL', NULL, 0, NULL, 240, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez'), 'Horlama Protezi', 'Snoring Denture', 18290, 30, 0, 'TL', NULL, 0, NULL, 241, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez'), 'Kroşe İlavesi', 'Missing Clasp', 2180, 30, 0, 'TL', NULL, 0, NULL, 242, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez'), 'Metal İskelet Tamiri', 'Metal Framework Repair', 2190, 30, 0, 'TL', NULL, 0, NULL, 243, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez'), 'Okluzyon Düzenleme', 'Occlusion Correction', 5390, 30, 0, 'TL', NULL, 0, NULL, 244, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez'), 'Tek Çene Total (Tek Çene) (Kafesli)', 'Total Single Jaw (Single Jaw) (Caged)', 66000, 30, 0, 'TL', NULL, 0, NULL, 245, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez'), 'Protez Vuruğu Alma', 'Removing Denture Impact', 580, 30, 0, 'TL', NULL, 0, NULL, 246, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez'), 'Proteze Yumuşak Akrilik Uygulaması (Daimi Tek Çene)', 'Soft Acrylic Application to Dentures (Permanent Single Jaw)', 6690, 30, 0, 'TL', NULL, 0, NULL, 247, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez'), 'Proteze Yumuşak Akrilik Uygulaması (Geçici Tek Çene)', 'Soft Acrylic Application to Dentures (Temporary Single Jaw)', 4150, 30, 0, 'TL', NULL, 0, NULL, 248, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez'), 'Sürgülü Protez (Tek Çene)', 'Removable Denture (Single Jaw)', 77000, 30, 0, 'TL', NULL, 0, NULL, 249, true);

-- Protez Implantüstü
INSERT INTO treatments (category_id, title, title_en, price, discount_rate, cost, currency, tooth_type, duration_minutes, exam_type, sort_order, is_active) VALUES
  ((SELECT id FROM treatment_categories WHERE slug = 'protez-implantustu'), 'Implantüstü Kuron, Empress / E-max (Full Porselen)', 'Implant-Supported Crown, Empress / E-max (Full Porcelain)', 22000, 30, 0, 'TL', 1, 0, NULL, 250, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez-implantustu'), 'Implantüstü Kuron, Metal Destekli Porselen', 'Implant-Supported Crown, Metal-Supported Porcelain', 11550, 30, 0, 'TL', 1, 0, NULL, 251, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez-implantustu'), 'Implantüstü Kuron, Zirkonya (Monolitik)', 'Implant-Supported Crown, Zirconia (Monolithic)', 14850, 30, 0, 'TL', 1, 0, NULL, 252, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez-implantustu'), 'İmplantüstü kuron, Zirkonya (Tabakalama)', 'Implant-Supported Crown, Zirconia (Layered)', 16500, 30, 0, 'TL', 1, 0, NULL, 253, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez-implantustu'), 'All-On-Four Daimi Protez (Ekonomik Implant)', 'All-On-Four Permanent Denture (Economical Implant)', 80850, 30, 0, 'TL', NULL, 0, NULL, 254, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez-implantustu'), 'All-On-Four Daimi Protez (Premium Implant)', 'All-On-Four Permanent Denture (Premium Implant)', 115500, 30, 0, 'TL', NULL, 0, NULL, 255, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez-implantustu'), 'All-On-Four Daimi Protez (Standart Implant)', 'All-On-Four Permanent Denture (Standard Implant)', 101060, 30, 0, 'TL', NULL, 0, NULL, 256, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez-implantustu'), 'All-On-Four Geçici Protez (Ekonomik Implant)', 'All-On-Four Temporary Denture (Economical Implant)', 22140, 30, 0, 'TL', NULL, 0, NULL, 257, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez-implantustu'), 'All-On-Four Geçici Protez (Premium Implant)', 'All-On-Four Temporary Denture (Premium Implant)', 30800, 30, 0, 'TL', NULL, 0, NULL, 258, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez-implantustu'), 'All-On-Four Geçici Protez (Standart Implant)', 'All-On-Four Temporary Denture (Standard Implant)', 24060, 30, 0, 'TL', NULL, 0, NULL, 259, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez-implantustu'), 'Ball Ataçman (Tek Çene)', 'Ball Attachment (Single Jaw)', 77000, 30, 0, 'TL', NULL, 0, NULL, 260, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez-implantustu'), 'Barlı Protez (Tek Çene)', 'Bar-Retained Denture (Single Jaw)', 93500, 30, 0, 'TL', NULL, 0, NULL, 261, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez-implantustu'), 'Custom Titanyum Abutment', 'Custom Titanium Abutment', 4040, 30, 0, 'TL', NULL, 0, NULL, 262, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez-implantustu'), 'Custom Zirkonya Abutment', 'Custom Zirconia Abutment', 9900, 30, 0, 'TL', NULL, 0, NULL, 263, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez-implantustu'), 'Geçici Hareketli Protez (Tek Çene)', 'Temporary Removable Denture (Single Jaw)', 8855, 30, 0, 'TL', NULL, 0, NULL, 264, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez-implantustu'), 'Geçici Kuron (İmplantüstü, Abutment Dahil)', 'Temporary Crown (Implant-Supported, Abutment) Included)', 4430, 30, 0, 'TL', NULL, 0, NULL, 265, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez-implantustu'), 'Geçici Sabit Protez (Tek Çene)', 'Temporary Fixed Prosthesis (Single Jaw)', 22140, 30, 0, 'TL', NULL, 0, NULL, 266, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez-implantustu'), 'Hibrit Porselen (Tek Çene)', 'Hybrid Porcelain (Single Jaw)', 148500, 30, 0, 'TL', NULL, 0, NULL, 267, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez-implantustu'), 'Hibrit Tİ-BAR Zirkon (Tek Çene)', 'Hybrid TI-BAR Zirconia (Single Jaw)', 165000, 30, 0, 'TL', NULL, 0, NULL, 268, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez-implantustu'), 'Lastik Değişimi (Locator ve Ball Attaşman İçin)', 'Rubber Replacement (For Locator and Ball Attachment)', 3795, 30, 0, 'TL', NULL, 0, NULL, 269, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez-implantustu'), 'Multiunit Farkı (Açılı)', 'Multiunit Difference (Angle)', 4430, 30, 0, 'TL', NULL, 0, NULL, 270, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez-implantustu'), 'Multiunit Farkı (Düz)', 'Multiunit Difference (Straight)', 2500, 30, 0, 'TL', NULL, 0, NULL, 271, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'protez-implantustu'), 'Titanyum Bar Farkı (Zirkonyum Hibrit protezler için)', 'Titanium Bar Difference (For Zirconium Hybrid Prostheses)', 16500, 30, 0, 'TL', NULL, 0, NULL, 272, true);

-- Tedavi ve Endodonti
INSERT INTO treatments (category_id, title, title_en, price, discount_rate, cost, currency, tooth_type, duration_minutes, exam_type, sort_order, is_active) VALUES
  ((SELECT id FROM treatment_categories WHERE slug = 'tedavi-ve-endodonti'), 'Kompozit Dolgu 1 Yüzlü (Kole)', 'Composite Filling', 4330, 30, 0, 'TL', 1, 0, NULL, 273, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'tedavi-ve-endodonti'), 'Kompozit Dolgu 1 Yüzlü (O)', 'Composite Filling (O)', 4630, 30, 0, 'TL', 1, 0, NULL, 274, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'tedavi-ve-endodonti'), 'Kompozit Dolgu 2 Yüzlü (DO)', 'Composite Filling (DO)', 5440, 30, 0, 'TL', 1, 0, NULL, 275, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'tedavi-ve-endodonti'), 'Kompozit Dolgu 2 Yüzlü (MO)', 'Composite Filling (MO)', 5440, 30, 0, 'TL', 1, 0, NULL, 276, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'tedavi-ve-endodonti'), 'Kompozit Dolgu 3 Yüzlü (MOD)', 'Composite Filling (MOD)', 6450, 30, 0, 'TL', 1, 0, NULL, 277, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'tedavi-ve-endodonti'), 'Kompozit Estetik Dolgu (Bonding/Lamina/Veneer)', 'Composite Esthetic Filling (Bonding/Laminate Veneer)', 8470, 30, 0, 'TL', 1, 0, NULL, 278, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'tedavi-ve-endodonti'), 'Kompozit Diastema Kapama (Tek diş)', 'Composite Diastema Closure (Single Tooth)', 6710, 30, 0, 'TL', NULL, 0, NULL, 279, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'tedavi-ve-endodonti'), 'Kanal Tedavisi - 1 Kanal (Dolgu Hariç)', 'Root Canal Treatment - 1 Canal (Excluding Filling)', 7855, 30, 0, 'TL', 1, 0, NULL, 280, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'tedavi-ve-endodonti'), 'Kanal Tedavisi - 2 Kanal (Dolgu Hariç)', 'Root Canal Treatment - 2 Canals (Excluding Filling)', 9975, 30, 0, 'TL', 1, 0, NULL, 281, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'tedavi-ve-endodonti'), 'Kanal Tedavisi - 3 Kanal (Dolgu Hariç)', 'Root Canal Treatment - 3 Canals (Excluding Filling)', 11890, 30, 0, 'TL', 1, 0, NULL, 282, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'tedavi-ve-endodonti'), 'Kanal Tedavisi - 4 Kanal (Dolgu Hariç)', 'Root Canal Treatment - 4 Canals (Excluding Filling)', 13980, 30, 0, 'TL', 1, 0, NULL, 283, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'tedavi-ve-endodonti'), 'Kanal Tedavisi Tekrarı - 1 Kanal (Dolgu Hariç)', 'Repeat Root Canal Treatment - 1 Canal (Excluding Filling)', 9265, 30, 0, 'TL', 1, 0, NULL, 284, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'tedavi-ve-endodonti'), 'Kanal Tedavisi Tekrarı - 2 Kanal (Dolgu Hariç)', 'Repeat Root Canal Treatment - 2 Canals (Excluding Filling)', 11175, 30, 0, 'TL', 1, 0, NULL, 285, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'tedavi-ve-endodonti'), 'Kanal Tedavisi Tekrarı - 3 Kanal (Dolgu Hariç)', 'Repeat Root Canal Treatment - 3 Canals (Excluding Filling)', 13140, 30, 0, 'TL', 1, 0, NULL, 286, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'tedavi-ve-endodonti'), 'Kanal Tedavisi Tekrarı - 4 Kanal (Dolgu Hariç)', 'Repeat Root Canal Treatment - 4 Canals (Excluding Filling)', 15910, 30, 0, 'TL', 1, 0, NULL, 287, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'tedavi-ve-endodonti'), 'Kanalda Perforasyon Tamiri (MTA vb.)', 'Perforation in the Root Canal Repair (MTA, etc.)', 4235, 30, 0, 'TL', NULL, 0, NULL, 288, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'tedavi-ve-endodonti'), 'Kanaldan Kırılmış Materyal Çıkartılması', 'Removal of Fractured Material from the Root Canal', 3700, 30, 0, 'TL', NULL, 0, NULL, 289, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'tedavi-ve-endodonti'), 'Post+Core Fiber', 'Post + Core Fiber', 8840, 30, 0, 'TL', NULL, 0, NULL, 290, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'tedavi-ve-endodonti'), 'Everx Core', 'Everx Core', 2540, 30, 0, 'TL', NULL, 0, NULL, 291, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'tedavi-ve-endodonti'), 'Daimi Diş Amputasyon', 'Permanent Tooth Amputation', 9075, 30, 0, 'TL', NULL, 0, NULL, 292, true),
  ((SELECT id FROM treatment_categories WHERE slug = 'tedavi-ve-endodonti'), '', '', 0, 0, 0, 'TL', 1, 0, NULL, 293, true);

